### ISSUE TITLE
Incompatible with FabricSkyBoxes

### ISSUE THREAD

**Issue by SAJewers** [jmb05/caelum-refabricated#2]
Running Caelum Refabricated and FabricSkyBoxes together causes a crash: 

[crash-2023-08-11_12.05.12-client.txt](https://github.com/jmb05/caelum-refabricated/files/12322831/crash-2023-08-11_12.05.12-client.txt)

**Comment by jmb05** [comment]
I think Caelum Refabricated and FabricSkyBoxes are iinherently incompatible, because FabricSkyBoxes changes the skybox totally while Caelum Refabricated relies on the Minecraft rendering code.
