### ISSUE TITLE
Incompatible with Sodium Extra

### ISSUE THREAD

**Issue by GamingWithDudeAlt** [jmb05/caelum-refabricated#3]
Anytime you try launching the game with this mod and Sodium Extra, the game crashes. I'm using v1.0.1 of this mod with v0.5.1 of Sodium Extra. I already tried putting mixin.sky=false in the Sodium Extra config like the dev said to do, and it didn't fix it.
[crash-2023-08-24_18.26.16-client.txt](https://github.com/jmb05/caelum-refabricated/files/12434080/crash-2023-08-24_18.26.16-client.txt)
[latest.log](https://github.com/jmb05/caelum-refabricated/files/12434081/latest.log)

**Comment by jmb05** [comment]
You will have to disable the sun and moon rendering from Sodium Extra too by adding the option `mixin.sun_moon=false`
