### ISSUE TITLE
pehkui/iris incompat

### ISSUE THREAD

**Issue by jitterdev** [jmb05/caelum-refabricated#5]
whenever i use this mod it seems to cause an issue with pehkui and iris, doesnt occur without caelum though https://mclo.gs/awvftOf

**Comment by BioTechproject27** [comment]
You've got a whole mess of mods and errors there. I have used your exact version of these mods together and they work.

Sort out that mess and see when exactly that problem occurs, which mods are minimally required for this exact crash.
Especially mod creators don't have the time to sort through all of that, please do some work yourself.

Thank you!

**Comment by jmb05** [comment]
I too cannot reproduce this crash
