### ISSUE TITLE
Fabric Seasons support.

### ISSUE THREAD

**Issue by MagmaSlime123** [jmb05/caelum-refabricated#7]
Title. The mod most likely modifies the day/night cycles, which may cause issues.

**Comment by jmb05** [comment]
Are there actually any issues? I remember using the two mods together with no issues.

**Comment by MagmaSlime123** [comment]
Thought I'd open an issue since I'm unsure.

**Comment by jmb05** [comment]
If there is no apparent issue then there is no need to open one here.
